export type User = {
  id: string;
  teamId: string;
  name: string;
  deleted: boolean;
  color: string;
  realName: string;
  tz: string;
  tzLabel: string;
  tzOffset: number;
  profile: {
    avatarHash: string;
    statusText: string;
    statusEmoji: string;
    realName: string;
    displayName: string;
    realNameNormalized: string;
    displayNameNormalized: string;
    email: string;
    imageOriginal: string;
    image24: string;
    image32: string;
    image48: string;
    image72: string;
    image192: string;
    image512: string;
    team: string;
  };
  isAdmin: boolean;
  isOwner: boolean;
  isPrimaryOwner: boolean;
  isRestricted: boolean;
  isUltraRestricted: boolean;
  isBot: boolean;
  updated: number;
  isAppUser: boolean;
  has2fa: boolean;
};
