/**
 * The image object
 * Represents the url or the content of an image generated by the OpenAI API.
 *
 * b64_json
 * string
 * The base64-encoded JSON of the generated image, if response_format is b64_json.
 *
 * url
 * string
 * The URL of the generated image, if response_format is url (default).
 *
 * revised_prompt
 * string
 * The prompt that was used to generate the image, if there was any revision to the prompt.
 */

export interface Image {
  /**
   * The base64-encoded JSON of the generated image, if response_format is b64_json.
   */
  b64Json?: string;
  /**
   * The URL of the generated image, if response_format is url (default).
   */
  url?: string;
  /**
   * The prompt that was used to generate the image, if there was any revision to the prompt.
   */
  revisedPrompt?: string;
}
