/**
 * WEBHOOK
 * contact_center.business_hours_created
 * WEBHOOK
 * contact_center.business_hours_deleted
 * WEBHOOK
 * contact_center.business_hours_updated
 * WEBHOOK
 * contact_center.closure_created
 * WEBHOOK
 * contact_center.closure_deleted
 * WEBHOOK
 * contact_center.closure_updated
 * WEBHOOK
 * contact_center.engagement_consumer_answered
 * WEBHOOK
 * contact_center.engagement_consumer_ended
 * WEBHOOK
 * contact_center.engagement_consumer_notified
 * WEBHOOK
 * contact_center.engagement_disposition_added
 * WEBHOOK
 * contact_center.engagement_messaging_transcript_completed
 * WEBHOOK
 * contact_center.engagement_monitor_ended
 * WEBHOOK
 * contact_center.engagement_monitor_started
 * WEBHOOK
 * contact_center.engagement_note_added
 * WEBHOOK
 * contact_center.engagement_started
 * WEBHOOK
 * contact_center.engagement_takeover_started
 * WEBHOOK
 * contact_center.engagement_transfer_accepted
 * WEBHOOK
 * contact_center.engagement_transfer_canceled
 * WEBHOOK
 * contact_center.engagement_transfer_completed
 * WEBHOOK
 * contact_center.engagement_transfer_initiated
 * WEBHOOK
 * contact_center.engagement_transfer_queued
 * WEBHOOK
 * contact_center.engagement_transfer_rejected
 * WEBHOOK
 * contact_center.engagement_transfer_reserved
 * WEBHOOK
 * contact_center.engagement_transfer_timeout
 * WEBHOOK
 * contact_center.engagement_user_answered
 * WEBHOOK
 * contact_center.engagement_user_dtmf_sent
 * WEBHOOK
 * contact_center.engagement_user_ended
 * WEBHOOK
 * contact_center.engagement_user_hold
 * WEBHOOK
 * contact_center.engagement_user_muted
 * WEBHOOK
 * contact_center.engagement_user_unhold
 * WEBHOOK
 * contact_center.engagement_user_unmuted
 * WEBHOOK
 * contact_center.engagement_wrap_up_ended
 * WEBHOOK
 * contact_center.engagement_wrap_up_started
 * WEBHOOK
 * contact_center.queue_agent_assigned
 * WEBHOOK
 * contact_center.queue_agent_unassigned
 * WEBHOOK
 * contact_center.queue_created
 * WEBHOOK
 * contact_center.queue_deleted
 * WEBHOOK
 * contact_center.queue_inbound_sla_updated
 * WEBHOOK
 * contact_center.queue_operating_hours_updated
 * WEBHOOK
 * contact_center.queue_supervisor_assigned
 * WEBHOOK
 * contact_center.queue_supervisor_unassigned
 * WEBHOOK
 * contact_center.recording_completed
 * WEBHOOK
 * contact_center.recording_deleted
 * WEBHOOK
 * contact_center.recording_paused
 * WEBHOOK
 * contact_center.recording_permanently_deleted
 * WEBHOOK
 * contact_center.recording_resumed
 * WEBHOOK
 * contact_center.recording_started
 * WEBHOOK
 * contact_center.recording_stopped
 * WEBHOOK
 * contact_center.recording_transcript_completed
 * WEBHOOK
 * contact_center.task_canceled
 * WEBHOOK
 * contact_center.task_completed
 * WEBHOOK
 * contact_center.task_created
 * WEBHOOK
 * contact_center.task_deleted
 * WEBHOOK
 * contact_center.task_entered_queue
 * WEBHOOK
 * contact_center.task_exited_queue
 * WEBHOOK
 * contact_center.task_reservation_accepted
 * WEBHOOK
 * contact_center.task_reservation_canceled
 * WEBHOOK
 * contact_center.task_reservation_completed
 * WEBHOOK
 * contact_center.task_reservation_created
 * WEBHOOK
 * contact_center.task_reservation_rejected
 * WEBHOOK
 * contact_center.task_reservation_timeout
 * WEBHOOK
 * contact_center.task_updated
 * WEBHOOK
 * contact_center.user_created
 * WEBHOOK
 * contact_center.user_deleted
 * WEBHOOK
 * contact_center.user_login
 * WEBHOOK
 * contact_center.user_logout
 * WEBHOOK
 * contact_center.user_opt_in
 * WEBHOOK
 * contact_center.user_opt_out
 * WEBHOOK
 * contact_center.user_status_changed
 * WEBHOOK
 * contact_center.user_updated
 * WEBHOOK
 * contact_center.voicemail_transcript_completedWEBHOOK
 * contact_center.business_hours_created
 * WEBHOOK
 * contact_center.business_hours_deleted
 * WEBHOOK
 * contact_center.business_hours_updated
 * WEBHOOK
 * contact_center.closure_created
 * WEBHOOK
 * contact_center.closure_deleted
 * WEBHOOK
 * contact_center.closure_updated
 * WEBHOOK
 * contact_center.engagement_consumer_answered
 * WEBHOOK
 * contact_center.engagement_consumer_ended
 * WEBHOOK
 * contact_center.engagement_consumer_notified
 * WEBHOOK
 * contact_center.engagement_disposition_added
 * WEBHOOK
 * contact_center.engagement_messaging_transcript_completed
 * WEBHOOK
 * contact_center.engagement_monitor_ended
 * WEBHOOK
 * contact_center.engagement_monitor_started
 * WEBHOOK
 * contact_center.engagement_note_added
 * WEBHOOK
 * contact_center.engagement_started
 * WEBHOOK
 * contact_center.engagement_takeover_started
 * WEBHOOK
 * contact_center.engagement_transfer_accepted
 * WEBHOOK
 * contact_center.engagement_transfer_canceled
 * WEBHOOK
 * contact_center.engagement_transfer_completed
 * WEBHOOK
 * contact_center.engagement_transfer_initiated
 * WEBHOOK
 * contact_center.engagement_transfer_queued
 * WEBHOOK
 * contact_center.engagement_transfer_rejected
 * WEBHOOK
 * contact_center.engagement_transfer_reserved
 * WEBHOOK
 * contact_center.engagement_transfer_timeout
 * WEBHOOK
 * contact_center.engagement_user_answered
 * WEBHOOK
 * contact_center.engagement_user_dtmf_sent
 * WEBHOOK
 * contact_center.engagement_user_ended
 * WEBHOOK
 * contact_center.engagement_user_hold
 * WEBHOOK
 * contact_center.engagement_user_muted
 * WEBHOOK
 * contact_center.engagement_user_unhold
 * WEBHOOK
 * contact_center.engagement_user_unmuted
 * WEBHOOK
 * contact_center.engagement_wrap_up_ended
 * WEBHOOK
 * contact_center.engagement_wrap_up_started
 * WEBHOOK
 * contact_center.queue_agent_assigned
 * WEBHOOK
 * contact_center.queue_agent_unassigned
 * WEBHOOK
 * contact_center.queue_created
 * WEBHOOK
 * contact_center.queue_deleted
 * WEBHOOK
 * contact_center.queue_inbound_sla_updated
 * WEBHOOK
 * contact_center.queue_operating_hours_updated
 * WEBHOOK
 * contact_center.queue_supervisor_assigned
 * WEBHOOK
 * contact_center.queue_supervisor_unassigned
 * WEBHOOK
 * contact_center.recording_completed
 * WEBHOOK
 * contact_center.recording_deleted
 * WEBHOOK
 * contact_center.recording_paused
 * WEBHOOK
 * contact_center.recording_permanently_deleted
 * WEBHOOK
 * contact_center.recording_resumed
 * WEBHOOK
 * contact_center.recording_started
 * WEBHOOK
 * contact_center.recording_stopped
 * WEBHOOK
 * contact_center.recording_transcript_completed
 * WEBHOOK
 * contact_center.task_canceled
 * WEBHOOK
 * contact_center.task_completed
 * WEBHOOK
 * contact_center.task_created
 * WEBHOOK
 * contact_center.task_deleted
 * WEBHOOK
 * contact_center.task_entered_queue
 * WEBHOOK
 * contact_center.task_exited_queue
 * WEBHOOK
 * contact_center.task_reservation_accepted
 * WEBHOOK
 * contact_center.task_reservation_canceled
 * WEBHOOK
 * contact_center.task_reservation_completed
 * WEBHOOK
 * contact_center.task_reservation_created
 * WEBHOOK
 * contact_center.task_reservation_rejected
 * WEBHOOK
 * contact_center.task_reservation_timeout
 * WEBHOOK
 * contact_center.task_updated
 * WEBHOOK
 * contact_center.user_created
 * WEBHOOK
 * contact_center.user_deleted
 * WEBHOOK
 * contact_center.user_login
 * WEBHOOK
 * contact_center.user_logout
 * WEBHOOK
 * contact_center.user_opt_in
 * WEBHOOK
 * contact_center.user_opt_out
 * WEBHOOK
 * contact_center.user_status_changed
 * WEBHOOK
 * contact_center.user_updated
 * WEBHOOK
 * contact_center.voicemail_transcript_completed
 */

export type WebhookContactCenterEvent =
  | "contact_center.business_hours_created"
  | "contact_center.business_hours_deleted"
  | "contact_center.business_hours_updated"
  | "contact_center.closure_created"
  | "contact_center.closure_deleted"
  | "contact_center.closure_updated"
  | "contact_center.engagement_consumer_answered"
  | "contact_center.engagement_consumer_ended"
  | "contact_center.engagement_consumer_notified"
  | "contact_center.engagement_disposition_added"
  | "contact_center.engagement_messaging_transcript_completed"
  | "contact_center.engagement_monitor_ended"
  | "contact_center.engagement_monitor_started"
  | "contact_center.engagement_note_added"
  | "contact_center.engagement_started"
  | "contact_center.engagement_takeover_started"
  | "contact_center.engagement_transfer_accepted"
  | "contact_center.engagement_transfer_canceled"
  | "contact_center.engagement_transfer_completed"
  | "contact_center.engagement_transfer_initiated"
  | "contact_center.engagement_transfer_queued"
  | "contact_center.engagement_transfer_rejected"
  | "contact_center.engagement_transfer_reserved"
  | "contact_center.engagement_transfer_timeout"
  | "contact_center.engagement_user_answered"
  | "contact_center.engagement_user_dtmf_sent"
  | "contact_center.engagement_user_ended"
  | "contact_center.engagement_user_hold"
  | "contact_center.engagement_user_muted"
  | "contact_center.engagement_user_unhold"
  | "contact_center.engagement_user_unmuted"
  | "contact_center.engagement_wrap_up_ended"
  | "contact_center.engagement_wrap_up_started"
  | "contact_center.queue_agent_assigned"
  | "contact_center.queue_agent_unassigned"
  | "contact_center.queue_created"
  | "contact_center.queue_deleted"
  | "contact_center.queue_inbound_sla_updated"
  | "contact_center.queue_operating_hours_updated"
  | "contact_center.queue_supervisor_assigned"
  | "contact_center.queue_supervisor_unassigned"
  | "contact_center.recording_completed"
  | "contact_center.recording_deleted"
  | "contact_center.recording_paused"
  | "contact_center.recording_permanently_deleted"
  | "contact_center.recording_resumed"
  | "contact_center.recording_started"
  | "contact_center.recording_stopped"
  | "contact_center.recording_transcript_completed"
  | "contact_center.task_canceled"
  | "contact_center.task_completed"
  | "contact_center.task_created"
  | "contact_center.task_deleted"
  | "contact_center.task_entered_queue"
  | "contact_center.task_exited_queue"
  | "contact_center.task_reservation_accepted"
  | "contact_center.task_reservation_canceled"
  | "contact_center.task_reservation_completed"
  | "contact_center.task_reservation_created"
  | "contact_center.task_reservation_rejected"
  | "contact_center.task_reservation_timeout"
  | "contact_center.task_updated"
  | "contact_center.user_created"
  | "contact_center.user_deleted"
  | "contact_center.user_login"
  | "contact_center.user_logout"
  | "contact_center.user_opt_in"
  | "contact_center.user_opt_out"
  | "contact_center.user_status_changed"
  | "contact_center.user_updated"
  | "contact_center.voicemail_transcript_completed";
