import { OpenAI } from "../OpenAI";
import { HttpProxyResponse } from "@runlightyear/lightyear";

/**
 * @beta
 */
export interface CreateCompletionProps {
  /**
   * ID of the model to use. You can use the List models API to see all of your available models, or see our Model overview for descriptions of them.
   */
  model: string;

  /**
   * Defaults to <|endoftext|>
   * The prompt(s) to generate completions for, encoded as a string, array of strings, array of tokens, or array of token arrays.
   *
   * Note that <|endoftext|> is the document separator that the model sees during training, so if a prompt is not specified the model will generate as if from the beginning of a new document.
   */
  prompt?: string | string[];

  /**
   * Defaults to null
   * The suffix that comes after a completion of inserted text.
   */
  suffix?: string;

  /**
   *   Defaults to 16
   *   The maximum number of tokens to generate in the completion.
   *
   *   The token count of your prompt plus maxTokens cannot exceed the model's context length. Most models have a context length of 2048 tokens (except for the newest models, which support 4096).
   */
  maxTokens?: number;

  /**
   * Defaults to 1
   * What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer.
   *
   * We generally recommend altering this or topP but not both.
   */
  temperature?: number;

  /**
   * Defaults to 1
   * An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with topP probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered.
   *
   * We generally recommend altering this or temperature but not both.
   */
  topP?: number;

  /**
   * Defaults to 1
   * How many completions to generate for each prompt.
   *
   * Note: Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for maxTokens and stop.
   */
  n?: number;

  /**
   * Defaults to false
   * Whether to stream back partial progress. If set, tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a data: [DONE] message.
   */
  stream?: boolean;

  /**
   * Defaults to null
   * Include the log probabilities on the logprobs most likely tokens, as well the chosen tokens. For example, if logprobs is 5, the API will return a list of the 5 most likely tokens. The API will always return the logprob of the sampled token, so there may be up to logprobs+1 elements in the response.
   *
   * The maximum value for logprobs is 5. If you need more than this, please contact us through our Help center and describe your use case.
   */
  logprobs?: number | null;

  /**
   * Defaults to false
   * Echo back the prompt in addition to the completion
   */
  echo?: boolean;

  /**
   * Defaults to null
   * Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.
   */
  stop?: string | string[] | null;

  /**
   * Defaults to 0
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.
   *
   * See more information about frequency and presence penalties.
   */
  presencePenalty?: number;

  /**
   * Defaults to 0
   * Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.
   *
   * See more information about frequency and presence penalties.
   */
  frequencyPenalty?: number;

  /**
   * Defaults to 1
   * Generates bestOf completions server-side and returns the "best" (the one with the highest log probability per token). Results cannot be streamed.
   *
   * When used with n, bestOf controls the number of candidate completions and n specifies how many to return – bestOf must be greater than n.
   *
   * Note: Because this parameter generates many completions, it can quickly consume your token quota. Use carefully and ensure that you have reasonable settings for maxTokens and stop.
   */
  bestOf?: number;

  /**
   * Defaults to null
   * Modify the likelihood of specified tokens appearing in the completion.
   *
   * Accepts a json object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this tokenizer tool (which works for both GPT-2 and GPT-3) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.
   *
   * As an example, you can pass {"50256": -100} to prevent the <|endoftext|> token from being generated.
   */
  logitBias?: object | null;

  /**
   * A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. Learn more.
   */
  user?: string;
}

/**
 * @beta
 */
export interface CreateCompletionResponse extends HttpProxyResponse {
  data: {
    id: string;
    object: string;
    created: number;
    model: string;
    choices: Array<{
      text: string;
      index: number;
      logprobs: null;
      finishReason: string;
    }>;
    usage: {
      promptTokens: number;
      completionTokens: number;
      totalTokens: number;
    };
  };
}

export const createCompletion =
  (self: OpenAI) =>
  async (props: CreateCompletionProps): Promise<CreateCompletionResponse> => {
    const {
      model,
      prompt,
      suffix,
      maxTokens,
      temperature,
      topP,
      n,
      stream,
      logprobs,
      echo,
      stop,
      presencePenalty,
      frequencyPenalty,
      bestOf,
      logitBias,
      user,
    } = props;

    console.debug("model", model);

    return self.post({
      url: `/completions`,
      data: {
        model,
        prompt,
        suffix,
        max_tokens: maxTokens,
        temperature,
        top_p: topP,
        n,
        stream,
        logprobs,
        echo,
        stop,
        presence_penalty: presencePenalty,
        frequency_penalty: frequencyPenalty,
        best_of: bestOf,
        logit_bias: logitBias,
        user,
      },
    });
  };
